branches:
  only:
    - feature/backend
    - master
language: node_js
services: 
  - docker
node_js:  
  - 12
cache:
  directories:
    - backend/node_modules
env:
  global:
    - NODE_ENV=production
    - GCP_PROJECT_ID=carpooling-app-271518
    - CLOUD_RUN_SERVICE=carpool-api
    - CLOUD_RUN_REGION=us-central1
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install: 
  - cd backend/
  - openssl aes-256-cbc -K $encrypted_252072f00533_key -iv $encrypted_252072f00533_iv -in key.json.enc -out key.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source "$HOME/google-cloud-sdk/path.bash.inc" > /dev/null
  - gcloud auth activate-service-account --key-file=key.json
  - gcloud auth configure-docker
  - gcloud config set project "${GCP_PROJECT_ID}"
install: 
  - npm install
script: 
  - npm run doc
  - export IMAGE_NAME=us.gcr.io/carpooling-app-271518/api:$TRAVIS_COMMIT
  - docker build -t $IMAGE_NAME .
  - docker push $IMAGE_NAME
  - gcloud run deploy "${CLOUD_RUN_SERVICE}" --image="${IMAGE_NAME}" --platform=managed --region="${CLOUD_RUN_REGION}" --allow-unauthenticated
