branches:
 
only: a7unittest
language: android
install: true
dist: trusty
android:
    components:
        - platform-tools
        - tools
        - build-tools-29.0.2
        - android-29
        - extra-google-google_play_services
        
    before_install:
        - chmod +x gradlew
                
    script:
        - ./gradlew build
    