version: "3.7"
services:
  db:
    image: mysql:5.6
    volumes:
    - db_data:/var/lib/mysql
    - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
    ports:
    - 3306:3306
volumes:
    db_data: 
